### ISSUE TITLE
Bump compat for "ImageMorphology" to "0.4"?

### ISSUE THREAD

**Issue by kschertler** [JuliaImages/ImageSegmentation.jl#89]
Would it be possible to add a v0.4 compat to `ImageMorphology`? Currently the package uses
`ImageMorphology = "0.2.6, 0.3"`. See also 7b258696e848b868b47f1cf0a4ff179eec96f7d3.

**Comment by kschertler** [comment]
I just got aware of the related discussion w.r.t to `Images.jl` https://github.com/JuliaImages/Images.jl/pull/1011. It seems, we have to wait for `ImageMorphology v0.5` since the `v0.4` version is more like a preview version, as pointed out by @johnnychen94.

**Comment by johnnychen94** [comment]
Things are a bit different here: for Images.jl we'd like to hold on to ImageMorphology v0.5 because [Images reexports ImageMorphology](https://github.com/JuliaImages/Images.jl/blob/401d1465196bec298d2035a6c625af78244f04e7/src/Images.jl#L24) and reexport relationship means that any breaking changes introduced by ImageMorphology is a breaking changes for Images.jl. That's why bumping ImageMorphology compat for Images.jl is not happened yet.

But for ImageSegmentation, since ImageMorphology is simply a "pure" dependency, it's safe to bump the compatibility as long as the test passes.

I'm not actively coding for JuliaImages recently... @kschertler Would you like to submit a PR for this and ensure the test passes? I'd be happy to merge and tag a release for it.

**Comment by kschertler** [comment]
Thanks @johnnychen94 for merging!
